
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: da1kg83inmadiu
  pool: 5
  username: hqakwynbsqcksd
  password: efcbe14ea24052c0ecc227c151065d9e750bf665bd3722cd87d5608fb3123507
  timeout: 5000
  port: 5432
  host: ec2-52-22-161-59.compute-1.amazonaws.com

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3