
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: Rails.application.credentials.database[:adapter]
  encoding: Rails.application.credentials.database[:encoding]
  database: Rails.application.credentials.database[:database]
  pool: Rails.application.credentials.database[:pool]
  username: Rails.application.credentials.database[:username]
  password: Rails.application.credentials.database[:password]
  timeout: Rails.application.credentials.database[:timeout]
  port: Rails.application.credentials.database[:port]
  host: Rails.application.credentials.database[:host]
secret_key_base: Rails.application.credentials.secret_key_base

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3