
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: d7ch81lvc1rd06
  pool: 5
  username: vorincukmeaema
  password: 890525f9148db16e2a12087d767f033c7bf2d38e59906374f9679259c3291eb7
  timeout: 5000
  port: 5432
  host: ec2-54-159-107-189.compute-1.amazonaws.com

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3