
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: d5vig654lmrbiu
  pool: 5
  username: bdyfpddohhtsfe
  password: 0351b0568a2b569c7b65b6d12cd9723787026faba4c2ffe68dcfab98b239158f
  timeout: 5000
  port: 5432
  host: ec2-34-203-155-237.compute-1.amazonaws.com

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3